---
# Configuration file for ElasticAlerts process

# Default interval to run check in seconds
defaults:
  alert_period: "300"

# Elasticsearch node for queries
elasticsearch:
  host: "172.40.0.95"
  port: "9200"
  ssl: true
  username: "elastic"
  password: "fe9Chenoo"
  #query: {"query":{"match_all": {}}}
  #index_pattern: ["syniverse-*"]

# Configured alerts
alerts:
  # The name of the configured alert
  - name: "HLR Link Status"
    index_pattern: "msnhub-hlr-*"
    # The interval for checks in seconds, minutes, hours, or days (i.e.: 1s, 1m, 1h, 1d)
    time_period: "2m"
    frequency: ""
    field: "status"
    term: "OutOfService"
    negate: false
    recipient: ["support@dccllc.net","itsupport@cvtc.org","cmishmash@cvtc.org","alarming@cvtc.org"]

  - name: "911 Call"
    index_pattern: "packetbeat-ecrc-*"
    # The interval for checks in seconds, minutes, hours, or days (i.e.: 1s, 1m, 1h, 1d)
    time_period: "2m"
    frequency: ""
    field: "tags"
    term: "customerfilter"
    negate: false
    recipient: ["support@dccllc.net"]

#  - name: "Test Alert"
#    index_pattern: "opencellid"
#    time_period: "30d"
#    field: "cell"
#    term: "37821"
#    negate: false
#    recipient: ["pbrown@dccllc.net"]
        
output:
   smtp:
      enabled: true
      host: "smtp.gmail.com"
      username: "paulbrown4@gmail.com"
      password: "gHostP89er!@#"
      port: "587"
   console:
      enabled: true
   log:
      enabled: true
      path: "/var/log/ElasticAlerts"
   
