---
# Configuration file for ElasticAlerts process

# Default interval to run check in seconds
defaults:
  alert_period: "300"

# Elasticsearch node for queries
elasticsearch:
  host: "172.118.0.103"
  port: "9200"
  ssl: true
  username: "elastic"
  password: "fe9Chenoo"
  #query: {"query":{"match_all": {}}}
  #index_pattern: ["syniverse-*"]

# Configured alerts
alerts:
  # The name of the configured alert
  - name: "HLR Link Status"
    index_pattern: "syniverse-*"
    # The interval for checks in seconds, minutes, hours, or days (i.e.: 1s, 1m, 1h, 1d)
    time_period: "5m"
    frequency: ""
    field: "status"
    term: "OutOfService"
    negate: false
    recipient: "pbrown@dccllc.net"

  - name: "911 Call"
    index_pattern: "packetbeat-*"
    # The interval for checks in seconds, minutes, hours, or days (i.e.: 1s, 1m, 1h, 1d)
    time_period: "5m"
    frequency: ""
    field: "tags"
    term: "cusotmerfilter"
    negate: false
    recipient: "pbrown@dccllc.net"
    
output:
   smtp:
      enabled: true
      host: "smtp.gmail.com"
      username: "paulbrown4@gmail.com"
      password: "ghostP89!@#"
      port: "587"
   console:
      enabled: false
   
