---
# Configuration file for ElasticAlerts process

# Default interval to run check in seconds
defaults:
  alert_period: "300"

# Elasticsearch node for queries
elasticsearch:
  host: "172.40.0.95"
  port: "9200"
  ssl: true
  username: "elastic"
  password: "fe9Chenoo"
  #query: {"query":{"match_all": {}}}
  #index_pattern: ["syniverse-*"]

# Configured alerts
alerts:
  # The name of the configured alert
  - name: "alert-1"
    index_pattern: "mnshub-hlr-*"
    # The interval for checks in seconds, minutes, hours, or days (i.e.: 1s, 1m, 1h, 1d)
    time_period: "2d"
    frequency: ""
    # Define fields that must match to search as a list '{"<field_1>":"<value_1>","<field_2>":"<value_2"}'
    must: [ 'status:OutOfService','agent.name:BLUE-RT-A','agent.name:BLUE-RT-B' ]
    # Define fields that must NOT match to search as an array '{"<field_1>":"<value_1>","<field_2>":"<value_2"}'
    #must_not: {}
    recipient: ["<email_address>"]

#  - name: "alert-2"
#    index_pattern: "packetbeat-*"
#    # The interval for checks in seconds, minutes, hours, or days (i.e.: 1s, 1m, 1h, 1d)
#    time_period: "1h"
#    frequency: ""
#    field: "sip.method"
#    term: "INVITE"
#    negate: false
    
output:
   smtp:
      enabled: false
      host: "smtp.gmail.com"
      username: "<USERNAME>@gmail.com"
      password: "<PASSWORD>"
      port: "587"
   console:
      enabled: true
   log:
      enabled: false
      path: ""
