---
# Configuration file for ElasticAlerts process

# Default interval to run check in seconds
defaults:
  alert_period: "300"

# Elasticsearch node for queries
elasticsearch:
  host: "172.118.0.103"
  port: "9200"
  ssl: true
  username: "elastic"
  password: "fe9Chenoo"
  #query: {"query":{"match_all": {}}}
  #index_pattern: ["syniverse-*"]

# Configured alerts
alerts:
  # The name of the configured alert
  - name: "alert-1"
    index_pattern: "syniverse-*"
    # The interval for checks in seconds, minutes, hours, or days (i.e.: 1s, 1m, 1h, 1d)
    time_period: "1h"
    frequency: ""
    field: "statusCode"
    term: "4"
    negate: true

  - name: "alert-2"
    index_pattern: "packetbeat-*"
    # The interval for checks in seconds, minutes, hours, or days (i.e.: 1s, 1m, 1h, 1d)
    time_period: "1h"
    frequency: ""
    field: "sip.method"
    term: "INVITE"
    negate: false
    
output:
   smtp:
      enabled: true
      host: "smtp.gmail.com"
      username: "paulbrown4@gmail.com"
      password: "ghostP89!@#"
      port: "587"
   
